//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_LOADING                     156
#define IDB_PNG1                        165
#define IDB_PNG2                        166
#define IDB_Pacman_1_                   193
#define IDB_PACMAN_RIGHT_1              195
#define IDB_PACMAN_RIGHT_2              196
#define IDB_PACMAN_UP_1                 199
#define IDB_PACMAN_UP_2                 200
#define IDB_PACMAN_DOWN_1               201
#define IDB_PACMAN_DOWN_2               202
#define IDB_PACMAN_LEFT_1               203
#define IDB_PACMAN_LEFT_2               204
#define IDB_RED_DOWN_1                  205
#define IDB_RED_DOWN_2                  206
#define IDB_RED_LEFT_2                  208
#define IDB_RED_RIGHT_1                 209
#define IDB_RED_RIGHT_2                 210
#define IDB_RED_LEFT_1                  211
#define IDB_GOLST_BLUE_DOWN_1           212
#define IDB_GHOST_BLUE_DOWN_1           212
#define IDB_GOLST_BLUE_DOWN_2           213
#define IDB_GHOST_BLUE_DOWN_2           213
#define IDB_GOLST_RED_DOWN_1            214
#define IDB_GHOST_RED_DOWN_1            214
#define IDB_GOLST_RED_DOWN_2            215
#define IDB_GHOST_RED_DOWN_2            215
#define IDB_GOLST_RED_LEFT_1            216
#define IDB_GHOST_RED_LEFT_1            216
#define IDB_GOLST_RED_LEFT_2            217
#define IDB_GHOST_RED_LEFT_2            217
#define IDB_GOLST_RED_RIGHT_1           218
#define IDB_GHOST_RED_RIGHT_1           218
#define IDB_GOLST_RED_RIGHT_2           219
#define IDB_GHOST_RED_RIGHT_2           219
#define IDB_GHOST_BLUE_LEFT_1           224
#define IDB_GHOST_BLUE_LEFT_2           225
#define IDB_GHOST_BLUE_RIGHT_1          226
#define IDB_GHOST_BLUE_RIGHT_2          227
#define IDB_GHOST_PINK_DOWN_1           228
#define IDB_GHOST_PINK_DOWN_2           229
#define IDB_GHOST_PINK_LEFT_1           230
#define IDB_GHOST_PINK_LEFT_2           231
#define IDB_GHOST_PINK_RIGHT_1          232
#define IDB_GHOST_PINK_RIGHT_2          233
#define IDB_GHOST_ORANGE_DOWN_1         234
#define IDB_GHOST_ORANGE_DOWN_2         235
#define IDB_GHOST_ORANGE_LEFT_1         236
#define IDB_GHOST_ORANGE_LEFT_2         237
#define IDB_GHOST_ORANGE_RIGHT_1        238
#define IDB_GHOST_ORANGE_RIGHT_2        239
#define IDB_PACMAN_DIE_1                240
#define IDB_PACMAN_DIE_2                241
#define IDB_PACMAN_DIE_3                242
#define IDB_PACMAN_DIE_4                243
#define IDB_PACMAN_DIE_BLACK            244
#define IDB_BLACKBMP                    244
#define IDB_WALL_BLUE                   245
#define IDB_FOOD                        246
#define IDB_PNG3                        247
#define IDB_scoreText                   248
#define IDB_SCORE_TEXT                  248
#define IDB_BITMAP1                     249
#define IDB_LEVEL_TEXT                  249
#define IDB_MAGICFOOD                   250
#define IDB_BITMAP2                     253
#define IDB_LIFEMULTI                   253
#define IDB_GHOST_BLUE_1                255
#define IDB_GHOST_BLUE_2                256
#define IDB_GHOST_WHITE_1               257
#define IDB_BITMAP6                     258
#define IDB_GHOST_WHITE_2               258
#define IDB_GHOST_EYES_DOWN             259
#define IDB_WALL_GREEN                  260
#define IDB_WALL_RED                    261
#define IDB_BITMAP3                     262
#define IDB_BITMAP4                     263
#define IDB_LOGO                        263
#define IDB_START_ABOUT                 264
#define IDB_BITMAP7                     265
#define IDB_START_STARTGAME             265
#define IDB_START_ABOUT_GAMECONTENT     266
#define IDB_START_ABOUT_BACK            268
#define IDB_LABEL_OPERATIONKEY          269
#define IDB_LABEL_COMBINATION           269
#define IDB_LABEL_GAMECONTENT           270
#define IDB_BITMAP9                     271
#define IDB_LABEL_OPRATION              271
#define IDB_LABEL_OPERATION             271
#define IDB_START_ABOUT_GAMECOMBINATION 272
#define IDB_START_ABOUT_GAMEOPERATION   273
#define IDB_MAP1                        274
#define IDB_MAP2                        275
#define IDB_BITMAP5                     276
#define IDB_MAP3                        276
#define IDB_BITMAP8                     277
#define IDB_STARTLOGO                   277
#define IDB_OVER_COMPLETED              279
#define IDB_BITMAP11                    280
#define IDB_OVER_GAMEOVER               280
#define IDB_OVER_EXIT                   281
#define IDB_BITMAP12                    282
#define IDB_OVER_RESTART                282
#define IDB_Author                      283
#define IDB_GAMEAUTHOR                  283
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        284
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
